from django.core.management.base import BaseCommand
from products import models


class Command(BaseCommand):
    def handle(self, *args, **options):
        brands = [
            "A.P.C.",
            "A.P.C. Golf",
            "Acne Studios",
            "Ader Error",
            "Adidas",
            "Aesop",
            "Aime Leon Dore",
            "Alexander McQueen",
            "Ambush",
            "AMI",
            "Andersen Andersen",
            "Anti Social Social Club",
            "Apple",
            "Arc'teryx",
            "Asics",
            "Audio-Technica",
            "Auralee",
            "Autry",
            "Axel Arigato",
            "Balenciaga",
            "Balmuda",
            "Bang & Olufsen",
            "Bao Bao Issey Miyake",
            "BAPE",
            "Barbour",
            "Bearbrick",
            "Birkenstock",
            "Bottega Veneta",
            "Burberry",
            "Byredo",
            "C.P. Company",
            "Cactus Plant Flea Market",
            "Camper",
            "Canada Goose",
            "Cartier",
            "Casetify",
            "Casio",
            "CDG",
            "Celine",
            "Chanel",
            "Chloe",
            "Clarks",
            "Comme des Garcons",
            "Common Projects",
            "Converse",
            "Coperni",
            "COS",
            "Creed",
            "Crocs",
            "Dada",
            "Daniel Arsham",
            "Darkr8m Studio",
            "Denon",
            "Dior",
            "Diptyque",
            "Dr. Martens",
            "Drew House",
            "Dyson",
            "Essentials",
            "Fear of God",
            "Fendi",
            "Frederic Malle",
            "G/Fore",
            "Gallery Dept.",
            "Ganni",
            "Golden Goose",
            "Goyard",
            "Gucci",
            "Helen Kaminski",
            "Helinox",
            "Hermes",
            "Hidden NY",
            "Hoka One One",
            "Homme Plisse Issey Miyake",
            "Howlin",
            "Human Made",
            "Hunter",
            "IAB Studio",
            "IKEA",
            "Isabel Marant",
            "Jacquemus",
            "Jil Sander",
            "Jimmy Choo",
            "Jo Malone",
            "Jordan",
            "Juun.J",
            "Kaikai Kiki",
            "Kaws",
            "Keen",
            "Kenzo",
            "Kith",
            "Le Labo",
            "Lego",
            "Lemaire",
            "Loewe",
            "Logitech",
            "Longchamp",
            "Loro Piana",
            "Louis Vuitton",
            "Maison Kitsune",
            "Maison Margiela",
            "Malbon Golf",
            "Marni",
            "Marshall",
            "Medicom Toy",
            "Merrell",
            "Meta",
            "Microsoft",
            "Mihara Yasuhiro",
            "Miu Miu",
            "Mizuno",
            "MM6 Maison Margiela",
            "Moncler",
            "Montblanc",
            "Needles",
            "Neighborhood",
            "New Balance",
            "New Era",
            "Nike",
            "Nintendo",
            "NOS7",
            "Nvidia",
            "Oakley",
            "Off-White",
            "Oofos",
            "Our Legacy",
            "Palace",
            "Paraboot",
            "Patagonia",
            "Peaceminusone",
            "Peaches.",
            "Play Comme des Garcons",
            "Playmobil",
            "Pokemon",
            "Polo Ralph Lauren",
            "Porter",
            "Prada",
            "Puma",
            "PXG",
            "Queen Studios",
            "Ray-Ban",
            "Reebok",
            "Roger Vivier",
            "Rolex",
            "Sacai",
            "Saint Laurent",
            "Salomon",
            "Salvatore Ferragamo",
            "Samsung",
            "Sansan Gear",
            "Snow Peak",
            "Sony",
            "Soundlook",
            "Souvenir Official",
            "Starbucks",
            "Stone Island",
            "Stussy",
            "Suicoke",
            "Sunnei",
            "Supreme",
            "Swatch",
            "Telfar",
            "Ten C",
            "The North Face",
            "Thom Browne",
            "Thunderbolt Project",
            "Tiffany & Co.",
            "Timberland",
            "Tod's",
            "Tom Ford",
            "Tom Sachs",
            "Undermycar",
            "Uniqlo",
            "Valentino",
            "Vans",
            "Vinyl",
            "Vivienne Westwood",
            "Wooyoungmi",
            "Y-3",
            "Yeezy",
        ]
        for b in brands:
            models.Brand.objects.create(name=b)
        self.stdout.write(self.style.SUCCESS("Brands created!"))
